services:
  main:
    build:
      context: .
      secrets:
        - ssh_docker
    hostname: dev-env-main
    volumes:
      - ./mount:/mnt/host
    ports:
      - "2222:22"

secrets:
  ssh_docker:
    file: ~/.ssh/dev-env.pub
